// Generated by waldo 0.1.0 — do not edit.
//
// Shadows opencode's built-in "edit" tool so it acts on the waldo session's
// target instead of the local machine. Delete this file to restore the built-in.
import { tool } from "@opencode-ai/plugin"
import { execFile } from "node:child_process"

const WALDO = "/Users/boj/waldo/waldo"
const SESSION = "rtx"

function waldo(args, stdin) {
  return new Promise((resolve, reject) => {
    const child = execFile(
      WALDO, args,
      { env: { ...process.env, WALDO_SESSION: SESSION }, maxBuffer: 64 * 1024 * 1024, encoding: "utf8" },
      (err, stdout, stderr) => {
        // A non-zero status from the target is data the model should see, not
        // an exception: "the command failed" is a normal and useful answer.
        if (err && typeof err.code === "number") return resolve({ stdout, stderr, code: err.code })
        if (err) return reject(err)
        resolve({ stdout, stderr, code: 0 })
      },
    )
    if (stdin !== undefined) { child.stdin.write(stdin); child.stdin.end() }
  })
}

export default tool({
  description: "Edit a file on the remote target: replace oldString with newString. Fails unless oldString occurs exactly once, unless replaceAll is set.",
  args: { filePath: tool.schema.string().describe("absolute path on the target"), oldString: tool.schema.string().describe("the exact text to replace"), newString: tool.schema.string().describe("the replacement text"), replaceAll: tool.schema.boolean().optional().describe("replace every occurrence") },
  async execute(args, context) {
    const rd = await waldo(["fs", "read", args.filePath])
    if (rd.code !== 0) throw new Error(rd.stderr || "read failed")
    const occurrences = rd.stdout.split(args.oldString).length - 1
    if (occurrences === 0) throw new Error("oldString not found in " + args.filePath)
    if (occurrences > 1 && !args.replaceAll) throw new Error("oldString occurs " + occurrences + " times in " + args.filePath + "; pass replaceAll or a longer unique string")
    const updated = args.replaceAll ? rd.stdout.split(args.oldString).join(args.newString) : rd.stdout.replace(args.oldString, args.newString)
    const wr = await waldo(["fs", "write", args.filePath], updated)
    if (wr.code !== 0) throw new Error(wr.stderr || "write failed")
    return { title: args.filePath, output: "edited " + args.filePath + " (" + occurrences + " replacement" + (occurrences > 1 ? "s" : "") + ")" }
  },
})
