// Generated by waldo 0.1.0 — do not edit.
//
// Shadows opencode's built-in "write" tool so it acts on the waldo session's
// target instead of the local machine. Delete this file to restore the built-in.
import { tool } from "@opencode-ai/plugin"
import { execFile } from "node:child_process"

const WALDO = "/Users/boj/waldo/waldo"
const SESSION = "rtx"

function waldo(args, stdin) {
  return new Promise((resolve, reject) => {
    const child = execFile(
      WALDO, args,
      { env: { ...process.env, WALDO_SESSION: SESSION }, maxBuffer: 64 * 1024 * 1024, encoding: "utf8" },
      (err, stdout, stderr) => {
        // A non-zero status from the target is data the model should see, not
        // an exception: "the command failed" is a normal and useful answer.
        if (err && typeof err.code === "number") return resolve({ stdout, stderr, code: err.code })
        if (err) return reject(err)
        resolve({ stdout, stderr, code: 0 })
      },
    )
    if (stdin !== undefined) { child.stdin.write(stdin); child.stdin.end() }
  })
}

export default tool({
  description: "Write a file on the remote target, replacing its contents.",
  args: { filePath: tool.schema.string().describe("absolute path on the target"), content: tool.schema.string() },
  async execute(args, context) {
    const r = await waldo(["fs", "write", args.filePath], args.content)
    if (r.code !== 0) throw new Error(r.stderr || "write failed")
    return { title: args.filePath, output: "wrote " + args.content.length + " bytes to " + args.filePath }
  },
})
