package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/bojieli/waldo/internal/session"
)

// opencodeToolTemplate generates one shadowing tool.
//
// opencode documents that a custom tool whose filename matches a built-in takes
// precedence over it. That makes opencode the only harness where waldo needs no
// workaround at all: no envelope parsing, no denied tools, no mirror. The model
// still sees `read` and `bash`, exactly as it always does, and they act on the
// target.
//
// Each file is generated self-contained rather than importing a shared helper,
// because opencode treats every file in the tool directory as a tool and a
// shared module sitting there would be loaded as one.
const opencodeToolTemplate = `// Generated by waldo %s — do not edit.
//
// Shadows opencode's built-in "%s" tool so it acts on the waldo session's
// target instead of the local machine. Delete this file to restore the built-in.
import { tool } from "@opencode-ai/plugin"
import { execFile } from "node:child_process"

const WALDO = %q
const SESSION = %q

function waldo(args, stdin) {
  return new Promise((resolve, reject) => {
    const child = execFile(
      WALDO, args,
      { env: { ...process.env, WALDO_SESSION: SESSION }, maxBuffer: 64 * 1024 * 1024, encoding: "utf8" },
      (err, stdout, stderr) => {
        // A non-zero status from the target is data the model should see, not
        // an exception: "the command failed" is a normal and useful answer.
        if (err && typeof err.code === "number") return resolve({ stdout, stderr, code: err.code })
        if (err) return reject(err)
        resolve({ stdout, stderr, code: 0 })
      },
    )
    if (stdin !== undefined) { child.stdin.write(stdin); child.stdin.end() }
  })
}

export default tool({
  description: %q,
  args: %s,
  async execute(args, context) {
%s
  },
})
`

type opencodeTool struct {
	name        string
	description string
	args        string
	body        string
}

// opencodeTools are the built-ins waldo shadows.
//
// Only names confirmed present in the opencode binary are shadowed. Shadowing a
// name that is not a built-in would silently *add* a tool rather than replace
// one, changing what the model sees — the exact thing this design exists to
// avoid.
var opencodeTools = []opencodeTool{
	{
		name:        "bash",
		description: "Execute a shell command on the remote target. Paths are the target's own absolute paths; do not translate them.",
		args:        `{ command: tool.schema.string().describe("the shell command to run"), description: tool.schema.string().optional().describe("what this command does") }`,
		body: `    const r = await waldo(["exec", "--", args.command])
    const out = [r.stdout, r.stderr].filter(Boolean).join("\n")
    return { title: args.command, output: out || "(no output)", metadata: { exit: r.code } }`,
	},
	{
		name:        "read",
		description: "Read a file from the remote target.",
		args:        `{ filePath: tool.schema.string().describe("absolute path on the target"), offset: tool.schema.number().optional(), limit: tool.schema.number().optional() }`,
		body: `    const a = ["fs", "read", args.filePath]
    if (args.offset) a.push("--offset", String(args.offset))
    if (args.limit) a.push("--limit", String(args.limit))
    const r = await waldo(a)
    if (r.code !== 0) throw new Error(r.stderr || "read failed")
    return { title: args.filePath, output: r.stdout }`,
	},
	{
		name:        "write",
		description: "Write a file on the remote target, replacing its contents.",
		args:        `{ filePath: tool.schema.string().describe("absolute path on the target"), content: tool.schema.string() }`,
		body: `    const r = await waldo(["fs", "write", args.filePath], args.content)
    if (r.code !== 0) throw new Error(r.stderr || "write failed")
    return { title: args.filePath, output: "wrote " + args.content.length + " bytes to " + args.filePath }`,
	},
	{
		name:        "edit",
		description: "Edit a file on the remote target: replace oldString with newString. Fails unless oldString occurs exactly once, unless replaceAll is set.",
		args:        `{ filePath: tool.schema.string().describe("absolute path on the target"), oldString: tool.schema.string().describe("the exact text to replace"), newString: tool.schema.string().describe("the replacement text"), replaceAll: tool.schema.boolean().optional().describe("replace every occurrence") }`,
		body: `    const rd = await waldo(["fs", "read", args.filePath])
    if (rd.code !== 0) throw new Error(rd.stderr || "read failed")
    const occurrences = rd.stdout.split(args.oldString).length - 1
    if (occurrences === 0) throw new Error("oldString not found in " + args.filePath)
    if (occurrences > 1 && !args.replaceAll) throw new Error("oldString occurs " + occurrences + " times in " + args.filePath + "; pass replaceAll or a longer unique string")
    const updated = args.replaceAll ? rd.stdout.split(args.oldString).join(args.newString) : rd.stdout.replace(args.oldString, args.newString)
    const wr = await waldo(["fs", "write", args.filePath], updated)
    if (wr.code !== 0) throw new Error(wr.stderr || "write failed")
    return { title: args.filePath, output: "edited " + args.filePath + " (" + occurrences + " replacement" + (occurrences > 1 ? "s" : "") + ")" }`,
	},
	{
		name:        "list",
		description: "List a directory on the remote target.",
		args:        `{ path: tool.schema.string().describe("absolute directory path on the target") }`,
		body: `    const r = await waldo(["fs", "ls", args.path])
    if (r.code !== 0) throw new Error(r.stderr || "list failed")
    return { title: args.path, output: r.stdout || "(empty)" }`,
	},
	{
		name:        "glob",
		description: "Find files matching a pattern on the remote target.",
		args:        `{ pattern: tool.schema.string(), path: tool.schema.string().optional().describe("root directory on the target") }`,
		body: `    const a = ["fs", "glob", args.pattern]
    if (args.path) a.push(args.path)
    const r = await waldo(a)
    if (r.code !== 0) throw new Error(r.stderr || "glob failed")
    return { title: args.pattern, output: r.stdout || "(no matches)" }`,
	},
	{
		name:        "grep",
		description: "Search file contents on the remote target. The search runs on the target, so only matches cross the network.",
		args:        `{ pattern: tool.schema.string(), path: tool.schema.string().optional(), include: tool.schema.string().optional().describe("glob restricting which files are searched") }`,
		body: `    const a = ["fs", "grep", args.pattern]
    if (args.path) a.push(args.path)
    if (args.include) a.push("--glob", args.include)
    const r = await waldo(a)
    if (r.code !== 0) throw new Error(r.stderr || "grep failed")
    return { title: args.pattern, output: r.stdout || "(no matches)" }`,
	},
}

const opencodeUsage = `waldo opencode — shadow opencode's built-in tools

  waldo opencode install [--global]   generate the shadowing tools
  waldo opencode uninstall [--global] remove them

Without --global the tools are written to ./.opencode/tool, which applies to the
current project only. With --global they go to ~/.config/opencode/tool.
`

func cmdOpencode(_ context.Context, args []string) error {
	fs := newFlagSet("opencode")
	sessName := fs.String("session", "", "session name (default $WALDO_SESSION)")
	global := fs.Bool("global", false, "install into ~/.config/opencode/tool instead of ./.opencode/tool")
	pos, err := parseFlags(fs, args)
	if err != nil {
		return err
	}
	action := "install"
	if len(pos) > 0 {
		action = pos[0]
	}
	if action != "install" && action != "uninstall" {
		fmt.Fprint(os.Stderr, opencodeUsage)
		return fmt.Errorf("unknown action %q", action)
	}

	dir, err := opencodeToolDir(*global)
	if err != nil {
		return err
	}

	if action == "uninstall" {
		var removed int
		for _, t := range opencodeTools {
			if err := os.Remove(filepath.Join(dir, t.name+".ts")); err == nil {
				removed++
			}
		}
		fmt.Printf("removed %d generated tools from %s\n", removed, dir)
		return nil
	}

	name := sessionNameFromEnv(*sessName)
	s, err := session.Load(name)
	if err != nil {
		return err
	}
	self, err := os.Executable()
	if err != nil {
		return err
	}
	// Resolve symlinks so the tool template embeds the real binary path, not a
	// dangling link. Ignore the error — the tool still works with the unresolved
	// path (it's a valid executable), and EvalSymlinks can fail legitimately on
	// some filesystems or in sandboxed environments.
	if resolved, rerr := filepath.EvalSymlinks(self); rerr == nil {
		self = resolved
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	for _, t := range opencodeTools {
		content := fmt.Sprintf(opencodeToolTemplate,
			version(), t.name, self, name, t.description, t.args, t.body)
		p := filepath.Join(dir, t.name+".ts")
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", p, err)
		}
	}

	fmt.Printf("installed %d shadowing tools in %s\n", len(opencodeTools), dir)
	fmt.Printf("  session  %s -> %s\n", name, s.Target.Describe())
	fmt.Printf("  tools    %s\n", toolNames())
	fmt.Print("\nopencode's built-ins of these names are now backed by the target.\n")
	fmt.Print("Restore them with: waldo opencode uninstall\n")
	return nil
}

func toolNames() string {
	names := make([]string, 0, len(opencodeTools))
	for _, t := range opencodeTools {
		names = append(names, t.name)
	}
	return strings.Join(names, ", ")
}

func opencodeToolDir(global bool) (string, error) {
	if global {
		if xdg := os.Getenv("XDG_CONFIG_HOME"); xdg != "" {
			return filepath.Join(xdg, "opencode", "tool"), nil
		}
		home, err := os.UserHomeDir()
		if err != nil {
			return "", err
		}
		return filepath.Join(home, ".config", "opencode", "tool"), nil
	}
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	return filepath.Join(cwd, ".opencode", "tool"), nil
}
