// Package envelope parses the command wrappers that harnesses place around a
// user's shell command.
//
// Harnesses do not hand a shell the command the model wrote. They wrap it with
// environment restoration and bookkeeping that assumes the command runs on the
// same machine as the harness. Forwarding that wrapper verbatim to a remote
// host is wrong in ways that are silent rather than loud, so waldo takes the
// wrapper apart, keeps what is portable, and reproduces the local bookkeeping
// itself.
package envelope

import (
	"regexp"
	"strings"
)

// Parsed is a decomposed harness command envelope.
type Parsed struct {
	// Command is the portable part, safe to run on the target.
	Command string

	// CwdFile is a path on the *local* machine where the harness expects the
	// post-command working directory to appear. Empty when the envelope had
	// no such bookkeeping.
	CwdFile string

	// StrippedSnapshot is true when a local shell-snapshot source was removed.
	StrippedSnapshot bool

	// Recognised is false when the envelope did not match any known shape. The
	// caller should then forward Command unchanged: an unrecognised wrapper is
	// a reason to be conservative, not a reason to guess.
	Recognised bool
}

var (
	// Matches: source '<path>' 2>/dev/null || true &&
	// The path is a local shell snapshot generated by the harness.
	snapshotRE = regexp.MustCompile(`^\s*(?:\.|source)\s+\S+\s+2>/dev/null\s*\|\|\s*true\s*&&\s*`)

	// Matches a trailing: && pwd -P >| <path>   (also >, and optional spaces)
	cwdRE = regexp.MustCompile(`\s*&&\s*pwd\s+-P\s*>\|?\s*(\S+)\s*$`)
)

// ParseClaudeCode decomposes a Claude Code shell envelope.
//
// The observed shape (Claude Code 2.1.233) is:
//
//	source <LOCAL_SNAPSHOT>.sh 2>/dev/null || true
//	  && { shopt -u extglob || setopt ... ; } >/dev/null 2>&1 || true
//	  && { \builtin unalias -- 'unsetenv'; ... ; } >/dev/null 2>&1 || true
//	  && eval '<USER COMMAND>' < /dev/null
//	  && pwd -P >| /tmp/claude-<rand>-cwd
//
// Two segments must not travel to the target.
//
// The snapshot is generated on the local machine and restores the *local*
// user's functions, aliases and PATH. Remotely it is at best a no-op, and it
// embeds the local username and directory layout — which, on a client's
// server, is an information disclosure waldo would be causing. It is stripped.
//
// The `pwd -P` redirect is how Claude Code persists `cd` between calls: it
// writes the resulting directory to a local temp file and reads it back after
// the command returns. Forwarded verbatim it would be written on the *remote*
// filesystem while the harness reads the local path, so `cd` would silently
// stop working, with no error anywhere. waldo strips it, records the path, and
// writes the resolved directory locally itself.
func ParseClaudeCode(raw string) Parsed {
	p := Parsed{Command: raw}

	if m := snapshotRE.FindString(raw); m != "" {
		p.Command = raw[len(m):]
		p.StrippedSnapshot = true
		p.Recognised = true
	}

	if m := cwdRE.FindStringSubmatch(p.Command); m != nil {
		p.CwdFile = m[1]
		p.Command = strings.TrimSpace(p.Command[:len(p.Command)-len(m[0])])
		p.Recognised = true
	}

	return p
}

// StripLocalPaths reports whether a command still mentions a local-only path
// that would leak the operator's directory layout to the target.
//
// waldo cannot rewrite arbitrary commands safely, so this is used to warn
// rather than to edit: a false positive that silently mangled a command would
// be far worse than a warning the operator can judge.
func StripLocalPaths(cmd string, localHome string) []string {
	var found []string
	if localHome == "" {
		return nil
	}
	for _, tok := range strings.Fields(cmd) {
		if strings.Contains(tok, localHome) {
			found = append(found, tok)
		}
	}
	return found
}
